- hosts: webserver
  become: yes
  roles:
    - apache2
    - common
  
  tags:
    web

- hosts: proxy
  become: yes
  roles:
    - common
    - nginx
  tags: proxy

- hosts: database
  become: yes
  roles:
    - common
    - mysql
  tags: database